/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    agents: Agent;
    'properties-sale': PropertiesSale;
    'properties-rent': PropertiesRent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    'properties-sale': PropertiesSaleSelect<false> | PropertiesSaleSelect<true>;
    'properties-rent': PropertiesRentSelect<false> | PropertiesRentSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (e.g. david, naz, rl-agent)
   */
  slug: string;
  profilePhoto?: (number | null) | Media;
  /**
   * Placeholder or external image URL when no upload
   */
  profilePhotoUrl?: string | null;
  email: string;
  phoneNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties-sale".
 */
export interface PropertiesSale {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  introText?: string | null;
  propertyType?: string | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  /**
   * Number of reception rooms
   */
  receptions?: number | null;
  /**
   * e.g. Sold, Under Offer, Available
   */
  status?: string | null;
  location?: string | null;
  price: string;
  description?: string | null;
  mainImage?: (number | null) | Media;
  /**
   * Placeholder or external image URL when no upload
   */
  mainImageUrl?: string | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  floorPlan?: (number | null) | Media;
  /**
   * YouTube, Vimeo, or direct video URL (e.g. https://www.youtube.com/watch?v=...)
   */
  videoUrl?: string | null;
  features?: string | null;
  tenure?: string | null;
  featured?: boolean | null;
  agent?: (number | null) | Agent;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties-rent".
 */
export interface PropertiesRent {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  introText?: string | null;
  propertyType?: string | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  /**
   * Number of reception rooms
   */
  receptions?: number | null;
  /**
   * e.g. Let Agreed, Available, Under Offer
   */
  status?: string | null;
  /**
   * e.g. £5,000
   */
  deposit?: string | null;
  /**
   * e.g. £500
   */
  holdingFee?: string | null;
  noAdminFee?: boolean | null;
  /**
   * Energy Performance Certificate rating (e.g. B, C)
   */
  epcRating?: string | null;
  location?: string | null;
  /**
   * e.g. £2,500 pcm
   */
  monthlyRent: string;
  description?: string | null;
  mainImage?: (number | null) | Media;
  /**
   * Placeholder or external image URL when no upload
   */
  mainImageUrl?: string | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  floorPlan?: (number | null) | Media;
  /**
   * YouTube, Vimeo, or direct video URL (e.g. https://www.youtube.com/watch?v=...)
   */
  videoUrl?: string | null;
  features?: string | null;
  featuredOnFrontPage?: boolean | null;
  agent?: (number | null) | Agent;
  familiesWelcome?: boolean | null;
  studentsAllowed?: boolean | null;
  petsAllowed?: boolean | null;
  smokersAllowed?: boolean | null;
  dssAllowed?: boolean | null;
  couplesAllowed?: boolean | null;
  liftAccess?: boolean | null;
  mapLat?: number | null;
  mapLng?: number | null;
  /**
   * Full address for map display
   */
  address?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'properties-sale';
        value: number | PropertiesSale;
      } | null)
    | ({
        relationTo: 'properties-rent';
        value: number | PropertiesRent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  profilePhoto?: T;
  profilePhotoUrl?: T;
  email?: T;
  phoneNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties-sale_select".
 */
export interface PropertiesSaleSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  introText?: T;
  propertyType?: T;
  bedrooms?: T;
  bathrooms?: T;
  receptions?: T;
  status?: T;
  location?: T;
  price?: T;
  description?: T;
  mainImage?: T;
  mainImageUrl?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  floorPlan?: T;
  videoUrl?: T;
  features?: T;
  tenure?: T;
  featured?: T;
  agent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties-rent_select".
 */
export interface PropertiesRentSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  introText?: T;
  propertyType?: T;
  bedrooms?: T;
  bathrooms?: T;
  receptions?: T;
  status?: T;
  deposit?: T;
  holdingFee?: T;
  noAdminFee?: T;
  epcRating?: T;
  location?: T;
  monthlyRent?: T;
  description?: T;
  mainImage?: T;
  mainImageUrl?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  floorPlan?: T;
  videoUrl?: T;
  features?: T;
  featuredOnFrontPage?: T;
  agent?: T;
  familiesWelcome?: T;
  studentsAllowed?: T;
  petsAllowed?: T;
  smokersAllowed?: T;
  dssAllowed?: T;
  couplesAllowed?: T;
  liftAccess?: T;
  mapLat?: T;
  mapLng?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}